pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

steps:
- task: Gulp@0
  displayName: 'gulp '
  inputs:
    publishJUnitResults: true
    enableCodeCoverage: true

- task: Npm@1
  displayName: 'npm pack'
  inputs:
    command: custom
    verbose: false
    customCommand: pack

- task: CopyFiles@2
  displayName: 'Copy Files to: drop'
  inputs:
    Contents: '*.tgz'
    TargetFolder: drop

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.SourcesDirectory)/drop
